export type CleaningLevel = 'raw' | 'clean' | 'broadcast'

export interface LocalizationRequest {
  text: string; sourceLanguage: string; targetLanguage: string; sceneContext: string; characterName: string; characterAge: string; characterPersonality: string[]; tone: string; emotion: string; culturalSettings: { preserveHumor: boolean; adaptReferences: boolean; regionalSlang: boolean }; cleaningLevel: CleaningLevel
}
export interface LocalizationResult { originalText: string; localizedText: string; detectedLanguage: string; slangDetected: string[]; culturalReferences: string[]; tone: string; emotion: string; adaptations: string[]; literalTranslation: string; qualityChecks: string[]; alternatives: string[] }
type Rule = { pattern: RegExp; value: string; label: string }
const rules: Record<string, Rule[]> = {
 Hindi: [{pattern:/\bbro\b/gi,value:'bhai',label:'bro → bhai'},{pattern:/\blit\b/gi,value:'ekdum mast',label:'lit → ekdum mast'},{pattern:/let['’]?s bounce/gi,value:'nikalte hain',label:"let's bounce → nikalte hain"},{pattern:/what['’]?s up/gi,value:'kya scene hai',label:"what's up → kya scene hai"},{pattern:/\bcool\b/gi,value:'sahi hai',label:'cool → sahi hai'},{pattern:/no way/gi,value:'aisa ho hi nahi sakta',label:'no way → aisa ho hi nahi sakta'}],
 Spanish: [{pattern:/\bbro\b/gi,value:'tío',label:'bro → tío'},{pattern:/\blit\b/gi,value:'increíble',label:'lit → increíble'},{pattern:/let['’]?s bounce/gi,value:'vámonos',label:"let's bounce → vámonos"},{pattern:/what['’]?s up/gi,value:'qué pasa',label:"what's up → qué pasa"}],
 French: [{pattern:/\bbro\b/gi,value:'mec',label:'bro → mec'},{pattern:/\blit\b/gi,value:'de folie',label:'lit → de folie'},{pattern:/let['’]?s bounce/gi,value:'on se casse',label:"let's bounce → on se casse"}],
 German: [{pattern:/\bbro\b/gi,value:'Bro',label:'bro → Bro'},{pattern:/\blit\b/gi,value:'mega',label:'lit → mega'},{pattern:/let['’]?s bounce/gi,value:'lass uns abhauen',label:"let's bounce → lass uns abhauen"}],
 Japanese: [{pattern:/\bbro\b/gi,value:'兄弟',label:'bro → 兄弟'},{pattern:/\blit\b/gi,value:'最高',label:'lit → 最高'}]
}
export function detectLanguage(text: string) { if(/[ऀ-ॿ]/.test(text)) return 'Hindi'; if(/[\u3040-\u30ff]/.test(text)) return 'Japanese'; if(/[\u4e00-\u9fff]/.test(text)) return 'Chinese'; return 'English' }
export function localize(request: LocalizationRequest): LocalizationResult { let localized=request.text; const adaptations:string[]=[]; const source=request.text+' '+request.sceneContext; const party=/party|club|concert|night|celebrat/i.test(source); for(const rule of rules[request.targetLanguage]??[]){ if(rule.pattern.test(localized)){ localized=localized.replace(rule.pattern,rule.value); adaptations.push(rule.label) } } if(request.cleaningLevel!=='raw') localized=localized.replace(/\b(damn|hell)\b/gi,request.cleaningLevel==='broadcast'?'':'really').replace(/\s{2,}/g,' ').trim(); if(request.characterPersonality.includes('Sarcastic')&&/crazy/i.test(localized)) localized+=' — wah, kya baat hai.'; const slang=['bro','lit',"let's bounce","what's up",'cool','no way'].filter(x=>new RegExp(x.replace(/[’']/g,"[’']"),'i').test(request.text)); const refs=party?['party culture','social invitation']:[]; const unsupported=!rules[request.targetLanguage]; if(unsupported) adaptations.push('Language available for future AI localization'); return {originalText:request.text,localizedText:localized, literalTranslation:request.text,detectedLanguage:request.sourceLanguage==='Auto Detect'?detectLanguage(request.text):request.sourceLanguage,slangDetected:slang,culturalReferences:refs,tone:request.tone,emotion:request.emotion,adaptations,qualityChecks:['Context checked',request.culturalSettings.adaptReferences?'Cultural references adapted':'Cultural references preserved'],alternatives:[localized,localized+' — naturally.',localized.replace(/!/g,' — okay?')].filter((v,i,a)=>v&&a.indexOf(v)===i)} }
export interface LocalizationProvider { localize(request: LocalizationRequest): Promise<LocalizationResult> }
export class LocalLocalizationProvider implements LocalizationProvider { async localize(request: LocalizationRequest){return localize(request)} }
export const sampleDialogue='Bro, this party is lit! Let\'s bounce.'
export const defaultRequest:LocalizationRequest={text:'',sourceLanguage:'Auto Detect',targetLanguage:'Hindi',sceneContext:'',characterName:'',characterAge:'',characterPersonality:[],tone:'Casual',emotion:'Excited',culturalSettings:{preserveHumor:true,adaptReferences:true,regionalSlang:true},cleaningLevel:'raw'}
export function parseSrt(text:string){return text.split(/\n\s*\n/).map(block=>{const lines=block.split(/\r?\n/);return {number:lines[0]??'',timestamp:lines[1]??'',text:lines.slice(2).join(' ')}}).filter(x=>x.timestamp.includes('-->'))}
export function toSrt(items:{number:string;timestamp:string;text:string}[]){return items.map(x=>[x.number,x.timestamp,x.text].join('\n')).join('\n\n')}
export function uid(){return `${Date.now()}-${Math.random().toString(36).slice(2,8)}`}
export type StoredHistory={id:string;createdAt:string;request:LocalizationRequest;result:LocalizationResult;rating?:number}
export function readStored<T>(key:string,fallback:T):T{if(typeof window==='undefined')return fallback;try{return JSON.parse(localStorage.getItem(key)||'null')??fallback}catch{return fallback}}
export function writeStored<T>(key:string,value:T){if(typeof window!=='undefined')localStorage.setItem(key,JSON.stringify(value))}
export const languages=[['Auto Detect','Global','Detection'],['English','Global','Language'],['Hindi','India','Language'],['Bengali','India','Language'],['Marathi','India','Language'],['Gujarati','India','Language'],['Punjabi','India','Language'],['Tamil','India','Language'],['Telugu','India','Language'],['Kannada','India','Language'],['Malayalam','India','Language'],['Odia','India','Language'],['Assamese','India','Language'],['Urdu','India','Language'],['Sanskrit','India','Language'],['Kashmiri','India','Language'],['Konkani','India','Language'],['Nepali','India','Language'],['Sindhi','India','Language'],['Maithili','India','Language'],['Manipuri','India','Language'],['Bodo','India','Language'],['Dogri','India','Language'],['Santali','India','Language'],['Haryanvi','India','Regional'],['Bhojpuri','India','Regional'],['Rajasthani','India','Regional'],['Awadhi','India','Regional'],['Braj','India','Regional'],['Magahi','India','Regional'],['Chhattisgarhi','India','Regional'],['Garhwali','India','Regional'],['Kumaoni','India','Regional'],['Marwari','India','Regional'],['Mewari','India','Regional'],['Malvi','India','Regional'],['Bundeli','India','Regional'],['Bagheli','India','Regional'],['Spanish','Global','Language'],['French','Global','Language'],['German','Global','Language'],['Italian','Global','Language'],['Portuguese','Global','Language'],['Russian','Global','Language'],['Arabic','Global','Language'],['Chinese','China','Language'],['Japanese','Japan','Language'],['Korean','Korea','Language'],['Turkish','Global','Language'],['Dutch','Global','Language'],['Polish','Global','Language'],['Ukrainian','Global','Language'],['Greek','Global','Language'],['Hebrew','Global','Language'],['Swedish','Global','Language'],['Norwegian','Global','Language'],['Danish','Global','Language'],['Finnish','Global','Language'],['Czech','Global','Language'],['Slovak','Global','Language'],['Hungarian','Global','Language'],['Romanian','Global','Language'],['Bulgarian','Global','Language'],['Serbian','Global','Language'],['Croatian','Global','Language'],['Indonesian','Global','Language'],['Malay','Global','Language'],['Thai','Global','Language'],['Vietnamese','Global','Language'],['Filipino','Global','Language'],['Swahili','Global','Language'],['Persian','Global','Language']].map(([name,region,type])=>({name,region,type}))
export const contexts=['Comedy','Romance','Action','Horror','College','Family','Professional','Emotional','Dramatic','Street Conversation','Thriller','Friendship','Political','Historical','Sports','Musical','Custom Context']
export const styles=['Casual','Formal','Fast','Slow','Energetic','Calm','Sarcastic','Dramatic','Soft','Aggressive']
